# This CloudBuild will be triggered by push to staging branch
#

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['echo', 'Building...']
  id: BUILD
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['echo', 'Testing...']
  id: TEST  
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - $_FUNCTION_NAME
  - --region=$_FUNCTION_REGION
  - --source=.
  - --trigger-http
  - --runtime=$_FUNCTION_RUNTIME
  - --project=$_FUNCTION_PROJECT_ID
  - --entry-point=$_ENTRY_POINT
  - --no-gen2  # ✅ Force deployment as Gen1 (avoids Cloud Run conflicts)
  - --quiet  # ✅ Avoids interactive prompts (e.g., unauthenticated access questions)
  id: DEPLOY

options:
  logging: CLOUD_LOGGING_ONLY  # Ensures logs are only sent to Cloud Logging
  
substitutions:
    _FUNCTION_PROJECT_ID : project-cicd-management  # Replace with actual Project ID
    _FUNCTION_NAME    : my-nodejs-app
    _FUNCTION_REGION  : us-central1
    _FUNCTION_RUNTIME : nodejs22
    _ENTRY_POINT      : helloWorld
