# This CloudBuild will be triggered by push to staging branch
#

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['echo', 'Building...']
  id: BUILD
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['echo', 'Testing...']
  id: TEST  

# ✅ Step to grant IAM permissions to Cloud Build before deploying the function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - projects
  - add-iam-policy-binding
  - $_FUNCTION_PROJECT_ID
  - --member=serviceAccount:$_CLOUD_BUILD_SERVICE_ACCOUNT
  - --role=roles/cloudfunctions.admin
  id: GRANT_IAM_PERMISSIONS

# ✅ Deploy the Cloud Function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - $_FUNCTION_NAME
  - --region=$_FUNCTION_REGION
  - --source=.
  - --trigger-http
  - --runtime=$_FUNCTION_RUNTIME
  - --project=$_FUNCTION_PROJECT_ID
  - --entry-point=$_ENTRY_POINT
  - --no-gen2  # ✅ Force Gen1 deployment (avoids Cloud Run conflicts)
  - --quiet  # ✅ Avoids interactive prompts (e.g., unauthenticated access)
  id: DEPLOY

# ✅ Step to make the function publicly accessible after deployment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gc
